Option Strict On
Option Explicit On
Imports TeaseAI.Common.Constants

Public Class ConvertTagLogic

    Public Function ConvertTag(oldTag As String) As ItemTagId
        Select Case oldTag.ToLower()
            Case "taghardCore"
                Return ItemTagId.Hardcore
            Case "taglesbian"
                Return ItemTagId.Lesbian
            Case "taggay"
                Return ItemTagId.Gay
            Case "tagbisexual"
                Return ItemTagId.Bisexual
            Case "tagsolof"
                Return ItemTagId.SoloFemale
            Case "tagsolom"
                Return ItemTagId.SoloMale
            Case "tagsolofuta"
                Return ItemTagId.SoloFuta
            Case "tagpov"
                Return ItemTagId.PointOfView
            Case "tagbondage"
                Return ItemTagId.Bondage
            Case "tagsm"
                Return ItemTagId.SadismAndMasochism
            Case "tagtd"
                Return ItemTagId.TeaseAndDenial
            Case "tagChastity"
                Return ItemTagId.Chastity
            Case "tagcfnm"
                Return ItemTagId.ClothedFemaleNakedMale
            Case "tagbath"
                Return ItemTagId.Bath
            Case "tagshower"
                Return ItemTagId.Shower
            Case "tagoutdoors"
                Return ItemTagId.Outdoors
            Case "tagartwork"
                Return ItemTagId.Artwork
            Case "tagmasturbation"
                Return ItemTagId.Masturbation
            Case "taghandjob"
                Return ItemTagId.Handjob
            Case "tagfingering"
                Return ItemTagId.Fingering
            Case "tagblowjob"
                Return ItemTagId.Blowjob
            Case "tagcunnilingus"
                Return ItemTagId.Cunnilingus
            Case "tagtitjob"
                Return ItemTagId.Titjob
            Case "tagfootjob"
                Return ItemTagId.Footjob
            Case "tagfacesitting"
                Return ItemTagId.Facesitting
            Case "tagrimming"
                Return ItemTagId.Rimming
            Case "tagmissionary"
                Return ItemTagId.Missionary
            Case "tagdoggystyle"
                Return ItemTagId.DoggyStyle
            Case "tagcowgirl"
                Return ItemTagId.Cowgirl
            Case "tagrcowgirl"
                Return ItemTagId.ReverseCowgirl
            Case "tagstanding"
                Return ItemTagId.Standing
            Case "taganalsex"
                Return ItemTagId.AnalSex
            Case "tagdp"
                Return ItemTagId.DoublePenetration
            Case "taggangbang"
                Return ItemTagId.Gangbang
            Case "tag1f"
                Return ItemTagId.OneWoman
            Case "tag2f"
                Return ItemTagId.TwoWomen
            Case "tag3f"
                Return ItemTagId.ThreeWomen
            Case "tag1m"
                Return ItemTagId.OneMan
            Case "tag2m"
                Return ItemTagId.TwoMen
            Case "tag3m"
                Return ItemTagId.ThreeMen
            Case "tag1futa"
                Return ItemTagId.OneFuta
            Case "tag2futa"
                Return ItemTagId.TwoFutas
            Case "tag3futa"
                Return ItemTagId.ThreeFutas
            Case "tagfemdom"
                Return ItemTagId.Femdom
            Case "tagmaledom"
                Return ItemTagId.Maledom
            Case "tagfutadom"
                Return ItemTagId.Futadom
            Case "tagfemsub"
                Return ItemTagId.Femsub
            Case "tagmalesub"
                Return ItemTagId.Malesub
            Case "tagfutasub"
                Return ItemTagId.Futasub
            Case "tagmultidom"
                Return ItemTagId.MultiDom
            Case "tagmultisub"
                Return ItemTagId.MultiSub
            Case "tagbodyface"
                Return ItemTagId.Face
            Case "tagbodyfingers"
                Return ItemTagId.Fingers
            Case "tagbodymouth"
                Return ItemTagId.Mouth
            Case "tagbodytits"
                Return ItemTagId.Tits
            Case "tagbodynipples"
                Return ItemTagId.Nipples
            Case "tagbodypussy"
                Return ItemTagId.Pussy
            Case "tagbodyass"
                Return ItemTagId.Ass
            Case "tagbodylegs"
                Return ItemTagId.Legs
            Case "tagbodyfeet"
                Return ItemTagId.Feet
            Case "tagbodycock"
                Return ItemTagId.Cock
            Case "tagbodyballs"
                Return ItemTagId.Balls
            Case "tagnurse"
                Return ItemTagId.Nurse
            Case "tagteacher"
                Return ItemTagId.Teacher
            Case "tagschoolgirl"
                Return ItemTagId.Schoolgirl
            Case "tagmaid"
                Return ItemTagId.Maid
            Case "tagsuperhero"
                Return ItemTagId.Superhero
            Case "tagmultisub"
                Return ItemTagId.MultiSub
            Case "tagwhipping"
                Return ItemTagId.Whipping
            Case "tagspanking"
                Return ItemTagId.Spanking
            Case "tagcocktorture"
                Return ItemTagId.CockTorture
            Case "tagballtorture"
                Return ItemTagId.BallTorture
            Case "tagstrapon"
                Return ItemTagId.StrapOn
            Case "tagblindfold"
                Return ItemTagId.Blindfold
            Case "taggag"
                Return ItemTagId.Gag
            Case "tagclamps"
                Return ItemTagId.Clamps
            Case "taghotwax"
                Return ItemTagId.HotWax
            Case "tagneedles"
                Return ItemTagId.Needles
            Case "tagelectro"
                Return ItemTagId.Electro
            Case "tagdomme"
                Return ItemTagId.TeaseAiDomme
            Case "tagcumshot"
                Return ItemTagId.Cumshot
            Case "tagcumeating"
                Return ItemTagId.CumEating
            Case "tagkissing"
                Return ItemTagId.Kissing
            Case "tagtattoos"
                Return ItemTagId.Tattoos
            Case "tagstockings"
                Return ItemTagId.Stockings
            Case "tagvibrator"
                Return ItemTagId.Vibrator
            Case "tagdildo"
                Return ItemTagId.Dildo
            Case "tagpocketpussy"
                Return ItemTagId.PocketPussy
            Case "taganaltoy"
                Return ItemTagId.AnalToy
            Case "tagwatersports"
                Return ItemTagId.Watersports
            Case "tagshibari"
                Return ItemTagId.Shibari
            Case "tagtentacles"
                Return ItemTagId.Tentacles
            Case "tagbukkake"
                Return ItemTagId.Bukkake
            Case "tagbakunyuu"
                Return ItemTagId.Bakunyuu
            Case "tagahegao"
                Return ItemTagId.Ahegao
            Case "tagbodywriting"
                Return ItemTagId.BodyWriting
            Case "tagtrap"
                Return ItemTagId.Trap
            Case "tagganguro"
                Return ItemTagId.Ganguro
            Case "tagmahoushoujo"
                Return ItemTagId.MahouShoujo
            Case "tagmonstergirl"
                Return ItemTagId.MonsterGirl
                ' Oddball tags found after the fact
            Case "td"
                Return ItemTagId.TeaseAndDenial
        End Select
        Throw New ArgumentOutOfRangeException()
    End Function

End Class
